# Generated by Django 6.0 on 2026-03-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('workout', 'Workout'), ('nutrition', 'Nutrition'), ('streak', 'Streak'), ('weight', 'Weight'), ('milestone', 'Milestone')], max_length=20)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('points', models.PositiveIntegerField(default=10)),
            ],
            options={
                'db_table': 'achievements',
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('workouts_completed', models.PositiveIntegerField(default=0)),
                ('total_duration_min', models.PositiveIntegerField(default=0)),
                ('calories_burned', models.FloatField(default=0)),
                ('calories_consumed', models.FloatField(default=0)),
                ('water_consumed_ml', models.FloatField(default=0)),
                ('steps', models.PositiveIntegerField(default=0)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('mood_score', models.PositiveIntegerField(blank=True, help_text='1-10 mood rating', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'daily_stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_achievements',
                'ordering': ['-earned_at'],
            },
        ),
    ]
