# Generated by Django 6.0 on 2026-03-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('serving_size', models.FloatField(default=100, help_text='Serving size in grams')),
                ('calories', models.FloatField(help_text='Calories per serving')),
                ('protein_g', models.FloatField(default=0)),
                ('carbs_g', models.FloatField(default=0)),
                ('fat_g', models.FloatField(default=0)),
                ('fiber_g', models.FloatField(default=0)),
                ('sugar_g', models.FloatField(default=0)),
                ('sodium_mg', models.FloatField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'food_items',
            },
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=15)),
                ('logged_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'meal_logs',
                'ordering': ['-logged_date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='MealLogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=1, help_text='Number of servings')),
            ],
            options={
                'db_table': 'meal_log_items',
            },
        ),
        migrations.CreateModel(
            name='NutritionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calories', models.FloatField(default=2000)),
                ('protein_g', models.FloatField(default=150)),
                ('carbs_g', models.FloatField(default=250)),
                ('fat_g', models.FloatField(default=65)),
                ('fiber_g', models.FloatField(default=25)),
                ('water_ml', models.FloatField(default=2500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nutrition_goals',
            },
        ),
        migrations.CreateModel(
            name='WaterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_ml', models.FloatField(help_text='Amount in millilitres')),
                ('logged_date', models.DateField()),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'water_logs',
                'ordering': ['-logged_at'],
            },
        ),
    ]
