# Generated by Django 6.0 on 2026-03-16 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutrition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_foods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meallog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meallogitem',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.fooditem'),
        ),
        migrations.AddField(
            model_name='meallogitem',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition.meallog'),
        ),
        migrations.AddField(
            model_name='nutritiongoal',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_goal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waterlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
